name: 🐛 Bug Report
description: Report a bug or issue with the O3DE Rider Plugin
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting this bug report
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported before
          required: true
        - label: I have read the documentation and troubleshooting guide
          required: true
        - label: I can reproduce this issue consistently
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows 10
        - Windows 11
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Ubuntu Linux
        - Other Linux Distribution
        - Other
    validations:
      required: true

  - type: input
    id: rider-version
    attributes:
      label: JetBrains Rider Version
      description: What version of JetBrains Rider are you using?
      placeholder: e.g., 2023.3.2
    validations:
      required: true

  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      description: What version of the O3DE Rider Plugin are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: input
    id: o3de-version
    attributes:
      label: O3DE Version
      description: What version of O3DE are you using?
      placeholder: e.g., 23.10.0
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: |
        Please include any relevant error logs, stack traces, or console output.
        You can find Rider logs in Help → Show Log in Explorer/Finder.
      placeholder: Paste error logs here...
      render: text

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop screenshots here or paste image URLs

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful...

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Low - Minor inconvenience
        - Medium - Affects functionality but has workaround
        - High - Blocks important functionality
        - Critical - Plugin unusable or data loss
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to fixing this bug?
      options:
        - label: I would like to work on fixing this bug
        - label: I can provide additional testing
        - label: I can help with documentation updates